/**
 * Classical Kids Resources Data
 * Book lists organized by age group
 */

const BOOKS_DATA = {
  "5-7": [
    { title: "The Jesus Storybook Bible", author: "Sally Lloyd-Jones", desc: "Must be read alongside Scripture for theological accuracy" },
    { title: "A Child's Garden of Verses", author: "Robert Louis Stevenson", desc: "Classic poetry that fosters appreciation for beauty" },
    { title: "Little Pilgrim's Progress", author: "Helen L. Taylor", desc: "A child-friendly retelling of The Pilgrim's Progress" },
    { title: "The Complete Tales of Beatrix Potter", author: "Beatrix Potter", desc: "Wholesome stories that teach responsibility and consequences" },
    { title: "Aesop's Fables", author: "Aesop", desc: "Classic fables with moral lessons" },
    { title: "Winnie-the-Pooh", author: "A.A. Milne", desc: "Gentle, wise, and joyful storytelling" },
    { title: "The Tale of Despereaux", author: "Kate DiCamillo", desc: "Themes of redemption, sacrifice, and courage" },
    { title: "The Story of Doctor Dolittle", author: "Hugh Lofting", desc: "A fun animal adventure" },
    { title: "Charlotte's Web", author: "E.B. White", desc: "Sacrificial love and friendship beautifully portrayed" },
    { title: "Blueberries for Sal", author: "Robert McCloskey", desc: "A delightful family-centered story" },
    { title: "The House at Pooh Corner", author: "A.A. Milne", desc: "Continuing themes of friendship and kindness" },
    { title: "Caps for Sale", author: "Esphyr Slobodkina", desc: "Lessons in patience and problem-solving" },
    { title: "Make Way for Ducklings", author: "Robert McCloskey", desc: "Themes of family, responsibility, and perseverance" },
    { title: "Curious George", author: "H.A. Rey", desc: "Encourages curiosity and problem-solving" },
    { title: "The Velveteen Rabbit", author: "Margery Williams", desc: "A profound allegory about love and selflessness" },
    { title: "Frog and Toad Are Friends", author: "Arnold Lobel", desc: "Teaches friendship and loyalty" },
    { title: "The Snowy Day", author: "Ezra Jack Keats", desc: "Encourages wonder in God's creation" },
    { title: "The Little Engine That Could", author: "Watty Piper", desc: "A classic lesson on perseverance" },
    { title: "The Story of Ping", author: "Marjorie Flack", desc: "Teaches obedience and responsibility" },
    { title: "Peter Rabbit's Giant Treasury", author: "Beatrix Potter", desc: "Classic British storytelling with moral lessons" }
  ],
  
  "8-10": [
    { title: "Dangerous Journey", author: "Oliver Hunkin", desc: "A beautifully illustrated retelling of The Pilgrim's Progress" },
    { title: "The Chronicles of Narnia", author: "C.S. Lewis", desc: "Christian allegory with profound biblical themes" },
    { title: "Little House on the Prairie", author: "Laura Ingalls Wilder", desc: "Emphasizes faith, family, and hard work" },
    { title: "Missionary Stories with the Millers", author: "Mildred A. Martin", desc: "Engaging missionary tales" },
    { title: "The Swiss Family Robinson", author: "Johann Wyss", desc: "Adventure with Christian values" },
    { title: "Tales of the Kingdom", author: "David & Karen Mains", desc: "Christian allegory with rich biblical imagery" },
    { title: "The Secret Garden", author: "Frances Hodgson Burnett", desc: "Themes of redemption and renewal" },
    { title: "The Green Ember (series)", author: "S.D. Smith", desc: "Christian allegory about courage and loyalty" },
    { title: "The Wind in the Willows", author: "Kenneth Grahame", desc: "Explores morality, virtue, and folly" },
    { title: "King Arthur and His Knights", author: "Roger Lancelyn Green", desc: "Explores heroism and honor" },
    { title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", desc: "Courage, sacrifice, and friendship" },
    { title: "The Mysterious Benedict Society", author: "Trenton Lee Stewart", desc: "Promotes wisdom and discernment" },
    { title: "The Wingfeather Saga", author: "Andrew Peterson", desc: "Christian allegory with deep biblical themes" },
    { title: "Island of the Blue Dolphins", author: "Scott O'Dell", desc: "Resilience and faith under adversity" },
    { title: "Black Beauty", author: "Anna Sewell", desc: "Kindness, justice, and compassion" },
    { title: "The Boxcar Children", author: "Gertrude Chandler Warner", desc: "Themes of perseverance and family" },
    { title: "Where the Red Fern Grows", author: "Wilson Rawls", desc: "Loyalty, love, and responsibility" },
    { title: "The Tale of Peter Rabbit", author: "Beatrix Potter", desc: "Classic moral lessons" }
  ],
  
  "11-13": [
    { title: "The Pilgrim's Progress", author: "John Bunyan", desc: "Essential Christian allegory" },
    { title: "Treasure Island", author: "Robert Louis Stevenson", desc: "Adventure with strong moral lessons" },
    { title: "Harry Potter (series)", author: "J.K. Rowling", desc: "Sacrifice, courage, and wisdom" },
    { title: "Anne of Green Gables", author: "L.M. Montgomery", desc: "Faith, virtue, and growing in grace" },
    { title: "The Hobbit", author: "J.R.R. Tolkien", desc: "Providence and humility" },
    { title: "Dr. Jekyll and Mr. Hyde", author: "Robert Louis Stevenson", desc: "A deep look at human depravity" },
    { title: "Twenty Thousand Leagues Under the Sea", author: "Jules Verne", desc: "Exploration and scientific wonder" },
    { title: "Journey to the Center of the Earth", author: "Jules Verne", desc: "Encourages curiosity and adventure" },
    { title: "The Chronicles of Prydain", author: "Lloyd Alexander", desc: "Fantasy with deep moral themes" },
    { title: "The Giver", author: "Lois Lowry", desc: "Explores free will and truth" },
    { title: "Robin Hood", author: "Howard Pyle", desc: "Justice and heroism" },
    { title: "Hatchet", author: "Gary Paulsen", desc: "Survival and responsibility" },
    { title: "Number the Stars", author: "Lois Lowry", desc: "Courage in the face of evil" },
    { title: "Old Yeller", author: "Fred Gipson", desc: "Sacrifice and loyalty" },
    { title: "Little Women", author: "Louisa May Alcott", desc: "Faith, virtue, and wisdom" },
    { title: "Tom Sawyer", author: "Mark Twain", desc: "Maturity and moral growth" },
    { title: "The Jungle Book", author: "Rudyard Kipling", desc: "Moral dilemmas and responsibility" },
    { title: "Brave New World", author: "Aldous Huxley", desc: "A critique of godless society" },
    { title: "Anne Frank: The Diary of a Young Girl", author: "Anne Frank", desc: "A young girl's faith in adversity" },
    { title: "The Call of the Wild", author: "Jack London", desc: "Survival, loyalty, and endurance" }
  ],
  
  "14-16": [
    { title: "The Lord of the Rings", author: "J.R.R. Tolkien", desc: "Epic tale of good vs evil, providence, and sacrifice" },
    { title: "Jane Eyre", author: "Charlotte Brontë", desc: "Faith, integrity, and moral courage" },
    { title: "Pride and Prejudice", author: "Jane Austen", desc: "Virtue, discernment, and humility" },
    { title: "Mere Christianity", author: "C.S. Lewis", desc: "Foundational Christian apologetics" },
    { title: "The Screwtape Letters", author: "C.S. Lewis", desc: "A witty look at spiritual warfare" },
    { title: "Fahrenheit 451", author: "Ray Bradbury", desc: "The danger of censorship and loss of truth" },
    { title: "Animal Farm", author: "George Orwell", desc: "Political allegory about power and corruption" },
    { title: "The Great Gatsby", author: "F. Scott Fitzgerald", desc: "The emptiness of materialism" },
    { title: "To Kill a Mockingbird", author: "Harper Lee", desc: "Justice, courage, and moral conviction" },
    { title: "The Scarlet Letter", author: "Nathaniel Hawthorne", desc: "Sin, guilt, and redemption" },
    { title: "Wuthering Heights", author: "Emily Brontë", desc: "The destructiveness of revenge and pride" },
    { title: "Great Expectations", author: "Charles Dickens", desc: "Class, ambition, and redemption" },
    { title: "The Picture of Dorian Gray", author: "Oscar Wilde", desc: "The consequences of vanity and sin" },
    { title: "Crime and Punishment", author: "Fyodor Dostoevsky", desc: "Guilt, redemption, and human nature" },
    { title: "The Hiding Place", author: "Corrie ten Boom", desc: "Faith under persecution" },
    { title: "Ender's Game", author: "Orson Scott Card", desc: "Ethics, leadership, and manipulation" },
    { title: "The Giver Quartet", author: "Lois Lowry", desc: "Free will, conformity, and humanity" },
    { title: "The Space Trilogy", author: "C.S. Lewis", desc: "Science fiction with deep theological themes" },
    { title: "Sense and Sensibility", author: "Jane Austen", desc: "Reason vs emotion, wisdom in balance" },
    { title: "The Chosen", author: "Chaim Potok", desc: "Faith, tradition, and friendship" }
  ],
  
  "17-18": [
    { title: "The Institutes of the Christian Religion", author: "John Calvin", desc: "Essential for understanding Reformed theology" },
    { title: "Bondage of the Will", author: "Martin Luther", desc: "Defends the biblical doctrine of total depravity" },
    { title: "The Holiness of God", author: "R.C. Sproul", desc: "Explores the majesty and fear of the Lord" },
    { title: "The Abolition of Man", author: "C.S. Lewis", desc: "Critique of moral relativism" },
    { title: "1984", author: "George Orwell", desc: "A critique of authoritarianism and loss of truth" },
    { title: "Pilgrim's Regress", author: "C.S. Lewis", desc: "An allegory of intellectual and spiritual journey" },
    { title: "Spiritual Disciplines for the Christian Life", author: "Donald Whitney", desc: "A practical guide to biblical growth" },
    { title: "The Reformed Pastor", author: "Richard Baxter", desc: "A model for deep Christian discipleship" },
    { title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", desc: "A masterwork on human depravity and redemption" },
    { title: "Les Misérables", author: "Victor Hugo", desc: "An epic story of grace and justice" },
    { title: "The Count of Monte Cristo", author: "Alexandre Dumas", desc: "A story of justice and forgiveness" },
    { title: "The Federalist Papers", author: "Hamilton, Madison, Jay", desc: "Understanding government through a biblical lens" },
    { title: "The Republic", author: "Plato", desc: "Non-Christian views on justice and virtue" },
    { title: "The Cost of Discipleship", author: "Dietrich Bonhoeffer", desc: "A challenge to follow Christ at all costs" },
    { title: "A Tale of Two Cities", author: "Charles Dickens", desc: "Sacrifice and redemption in revolutionary France" },
    { title: "Frankenstein", author: "Mary Shelley", desc: "Ethics of creation and consequences of human pride" },
    { title: "The Weight of Glory", author: "C.S. Lewis", desc: "Reflections on eternity and longings for heaven" },
    { title: "The Pursuit of God", author: "A.W. Tozer", desc: "Deepening one's relationship with God" },
    { title: "Desiring God", author: "John Piper", desc: "A call to delight in Christ-centered living" },
    { title: "Heaven", author: "Randy Alcorn", desc: "A biblical exploration of the afterlife and eternity" }
  ]
};

// Memory Work Playlists
// NOTE: Replace PLAYLIST_ID with actual playlist IDs from The Homeschool Helper YouTube channel
const MEMORY_PLAYLISTS = {
  cycle1: [
    { week: 1, topics: "Creation, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 2, topics: "Adam & Eve, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 3, topics: "Noah, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 4, topics: "Tower of Babel, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 5, topics: "Abraham, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 6, topics: "Isaac, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 7, topics: "Jacob, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 8, topics: "Joseph, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 9, topics: "Moses, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 10, topics: "Exodus, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 11, topics: "Ten Commandments, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 12, topics: "Joshua, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 13, topics: "Judges, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 14, topics: "Kings, Geography, Science", playlistId: "PLj3LbBY6HENRSwtf-QcIBsAVylZHrsVBl" },
    { week: 15, topics: "Prophets, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 16, topics: "Exile, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 17, topics: "Return, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 18, topics: "Intertestamental Period, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 19, topics: "Roman Empire, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 20, topics: "Early Church, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 21, topics: "Middle Ages, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 22, topics: "Feudalism, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 23, topics: "Crusades, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 24, topics: "Renaissance, Geography, Science", playlistId: "PLAYLIST_ID" }
  ],
  
  cycle2: [
    { week: 1, topics: "Medieval Europe, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 2, topics: "Renaissance, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 3, topics: "Reformation, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 4, topics: "Age of Exploration, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 5, topics: "Colonization, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 6, topics: "Scientific Revolution, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 7, topics: "Enlightenment, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 8, topics: "French Revolution, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 9, topics: "Napoleon, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 10, topics: "Industrial Revolution, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 11, topics: "Victorian Era, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 12, topics: "American Civil War, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 13, topics: "Imperialism, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 14, topics: "World War I, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 15, topics: "Russian Revolution, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 16, topics: "Roaring Twenties, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 17, topics: "Great Depression, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 18, topics: "World War II, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 19, topics: "Cold War, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 20, topics: "Space Race, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 21, topics: "Civil Rights, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 22, topics: "Vietnam War, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 23, topics: "Fall of Communism, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 24, topics: "Modern Era, Geography, Science", playlistId: "PLAYLIST_ID" }
  ],
  
  cycle3: [
    { week: 1, topics: "Native Americans, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 2, topics: "European Exploration, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 3, topics: "Jamestown, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 4, topics: "Plymouth, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 5, topics: "13 Colonies, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 6, topics: "Colonial Life, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 7, topics: "French & Indian War, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 8, topics: "Road to Revolution, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 9, topics: "Revolutionary War, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 10, topics: "Constitution, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 11, topics: "Early Republic, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 12, topics: "War of 1812, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 13, topics: "Westward Expansion, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 14, topics: "Manifest Destiny, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 15, topics: "Mexican-American War, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 16, topics: "Slavery & Abolition, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 17, topics: "Civil War, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 18, topics: "Reconstruction, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 19, topics: "Gilded Age, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 20, topics: "Progressive Era, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 21, topics: "World Wars, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 22, topics: "Post-War America, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 23, topics: "Modern Conflicts, Geography, Science", playlistId: "PLAYLIST_ID" },
    { week: 24, topics: "Contemporary America, Geography, Science", playlistId: "PLAYLIST_ID" }
  ]
};

console.log('📚 Resources data loaded successfully!');
